name: Generate TOC

on:
  push:
    paths:
      - 'guides/**/*.md'
  pull_request:
    paths:
      - 'guides/**/*.md'
  workflow_dispatch:
    

jobs:
  toc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install markdown-toc
      run: npm install -g markdown-toc

    - name: Generate TOC for all guides
      run: |
        for file in $(find guides -name '*.md'); do
          markdown-toc -i $file
        done
  
    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update TOC"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
