name: Lint Markdown

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install markdownlint
      run: npm install -g markdownlint-cli

    - name: Run markdownlint
      run: markdownlint '**/*.md' --fix
