name: ChatGPT Integration

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  chatgpt:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Issue or PR Details
      run: |
        echo "Issue/PR title: ${{ github.event.issue.title }}"
        echo "Issue/PR body: ${{ github.event.issue.body }}"

    - name: Post to ChatGPT
      run: |
        curl -X POST https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -d '{
            "model": "gpt-4",
            "messages": [{"role": "system", "content": "Summarize the following issue or pull request:"}, {"role": "user", "content": "${{ github.event.issue.body }}"}]
          }'
