name: ChatGPT Automation

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  chatgpt_interaction:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Fetch Issue or PR Details
      id: get_details
      run: |
        echo "Fetching issue/PR details..."
        echo "Issue/PR title: ${{ github.event.issue.title }}"
        echo "Issue/PR body: ${{ github.event.issue.body }}"
        echo "Issue/PR number: ${{ github.event.issue.number }}"
        echo "Issue/PR details fetched"

    - name: Call OpenAI API with ChatGPT
      id: chatgpt_response
      run: |
        response=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
        -d '{
          "model": "gpt-4o",
          "messages": [{"role": "system", "content": "Summarize the following issue or pull request:"}, {"role": "user", "content": "${{ github.event.issue.body }}"}]
        }' | jq -r '.choices[0].message.content')
        
        echo "Raw Response: $raw_response"

    - name: Comment on the Issue or PR
      run: |
        curl -s -X POST https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d "{\"body\":\"ChatGPT Response: ${{ steps.chatgpt_response.outputs.response }}\"}"
